import Head from 'next/head'
import styles from '../styles/Home.module.css'
// Font awesome example
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faSquareFacebook as facebook} from '@fortawesome/free-brands-svg-icons'
import {  } from '@fortawesome/free-solid-svg-icons'
import {  } from '@fortawesome/free-regular-svg-icons'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Tienda en linea Joyeria Kable</h1>
      <FontAwesomeIcon icon={facebook} />
    </div>
  )
}